
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/eifini?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMqVDLIhUxGwYKU2XVmTAD9ilMRr5vUysFF/5BcYM12eJacVUxqepJtSJJBmvENK/eVaJ4ok/OIiS3FjN1SA//sCAwEAAQ==
    username: root
    password: HXuwsPPSG48ZwkXHUVbK/ytgaRJLJ0LUB0++x0SM/qVzwzahhs2RKUUa5gU6zmuRCKv2HcRf+r0Pir/MeZ+MXA==